AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploying yggdrasil to lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Tracing: Active

Resources:
  YggdrasilFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${YggdrasilECRRepository}:latest
      ImageConfig:
        Command: ["run.sh"]
      Architectures:
        - x86_64
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: "2.0"
      Environment:
        Variables:
          NODE_ENV: production
          PORT: 3000
          AWS_LWA_ENABLE_COMPRESSION: "true"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
